name: CI + CD - DEV - artifact
 
on:
  push:
    branches: [ dev ]

jobs:

  Build:
    runs-on: ubuntu-latest
    steps:

      - name: 'Creating artifact download directory'
        run: mkdir downloads

      - uses: actions/checkout@v2

      - name: "Listing files"
        run: |
          pwd
          ls -la

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: downloads
          retention-days: 1

      - name: 'Echo download path'
        run: |
          echo ${{steps.download.outputs.download-path}}
          ls -laR ${{steps.download.outputs.download-path}}
  
  DeployRec:
    name: Deploiement en Dev / R7 
    # if: github.ref == 'refs/heads/dev'
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: PROD
      url: 'http://test.myapp.com/PROD'
    steps:

      - name: "Listing files"
        run: |
          pwd
          ls -la
      
      - name: 📂 Custom Sync files 
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_user }}
          # password: ${{ secrets.ftp_password }}
          port: ${{ secrets.ftp_port }}
          key: ${{ secrets.PERSONAL_SERVER_1_SSH_PRIVATE_KEY }}
          source: "*"
          target: "/home/ubuntu/GitHubAction/FTP"
          rm: true
   