name: CI + CD - DEV

on:
  push:
    branches: [ dev ]

jobs:

  DeployRec:
    name: Deploiement en Dev / R7 
    # if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    environment: 
      name: DEV
      url: 'http://test.myapp.com/'
    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: "REMOVE PROD File"
        run: |
          pwd
          ls -la
          rm -f prod.txt
      # - name: 📂 Sync files
      #   uses: SamKirkland/FTP-Deploy-Action@4.0.0
      #   with:
      #     server: ${{ secrets.ftp_server }}
      #     username: ${{ secrets.ftp_user }}
      #     password: ${{ secrets.ftp_password }}
      #     server-dir: githubaction/ 

      # - name: 📂 Sync files 
      #   uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      #   with:
      #     ftp_host: ${{ secrets.ftp_server }}
      #     ftp_username: ${{ secrets.ftp_user }}
      #     ftp_password: ${{ secrets.ftp_password }}
      #     delete: "true"
      #     local_source_dir: "./" #/home/runner/work/repo1/repo1
      #     dist_target_dir: "githubaction"
      #     exclude: "'^.git/' '^.github/'"

      
      # - name: 📂 Custom Sync files 
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.ftp_server }}
      #     username: ${{ secrets.ftp_user }}
      #     # password: ${{ secrets.ftp_password }}
      #     port: ${{ secrets.ftp_port }}
      #     key: ${{ secrets.PERSONAL_SERVER_1_SSH_PRIVATE_KEY }}
      #     source: "*"
      #     target: "/home/ubuntu/GitHubAction/FTP"
      #     rm: true


      - name: FTP Deployer
        uses: sand4rt/ftp-deployer@v1.3
        with:
          sftp: false # optional
          host: ${{ secrets.ftp_server }} # e.g. ftp.host.com or sftp.host.com
          port: 21 # optional, default is: 21
          username: ${{ secrets.ftp_user }} # FTP username
          password: ${{ secrets.ftp_password }} # FTP password
          remote_folder: githubaction # optional, remote path of your FTP server
          # cleanup: true # optional, remove existing files inside FTP remote folder
    