
name: Nom du workflow

# Trigger
#on:
#  push:
#    branches: [ master ]

jobs:

  # Job 1
  my_job_1:
    runs-on: self-hosted  # OS

    # Actions
    steps:
    - uses: actions/checkout@v2
    - run: echo 'Ceci est une commande unix'

    - name: "Directory"
      run: |
          pwd
          echo "List dir"
          ls -la

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_user }}
        password: ${{ secrets.ftp_password }}



